listen:
  - "::"
port: 8000
whitelistMode: false
whitelist:
  - 127.0.0.1
basicAuthMode: true
basicAuthUser:
  username: maomao
  password: "511630"
enableCorsProxy: false
securityOverride: false
autorun: true
disableThumbnails: false
thumbnailsQuality: 95
avatarThumbnailsPng: false
allowKeysExposure: false
skipContentCheck: false
disableChatBackup: false
requestOverrides: []
enableExtensions: true
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Xenova/all-mpnet-base-v2
  promptExpansionModel: Cohee/fooocus_expansion-onnx
  speechToTextModel: Xenova/whisper-small
  textToSpeechModel: Xenova/speecht5_tts
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
enableServerPlugins: false
